### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#263]
hi @stsrki 

Couple of issues : 

(1) I noticed that your `Tooltip` display an empty tooltip even when Text is "" (or null). 

![image](https://user-images.githubusercontent.com/26474006/65218401-98a52500-dae0-11e9-855d-e004cbe93986.png)

According to [Bootstrap Docs](https://getbootstrap.com/docs/4.3/components/tooltips/) "Tooltips with zero-length titles are never displayed."

Would you be able to fix this?

(2) Another issue, I have a Tooltip inside a fixed-width div

![image](https://user-images.githubusercontent.com/26474006/65216952-cc7e4b80-dadc-11e9-9904-3ab79dc4ad2a.png)

From memory, I think attaching the tooltip to the `body` element like this `data-container="body"` solves the issue, but I can't test it. Would you be able to expose a property called "Container" - because tooltips always have this issue since they need to float on top of everything

![image](https://user-images.githubusercontent.com/26474006/65217099-48789380-dadd-11e9-8544-25d6cb57a730.png)

Regards

Brett

**Comment by stsrki** [comment]
Hi @brettwinters 

1. I'm using custom implementation for `Tooltip` instead of _popper.js_ implementation that comes with Bootstrap. The reason is that I wanted to add support for all Blazorise providers without adding a third-party dependency. In this case the _popper.js_. Since my own implementation is fully done with css I will see what can be done for empty strings.

2. As stated in first answer adding this attribute will not help since the tooltip is custom made.

**Comment by brettwinters** [comment]
Also, while you're looking at enhancements the following features would also be useful: 

(1) Support for longer messages and allow the Environment.NewLine (CR, LF) within the message. Currently the message is truncated with an ellipses ("xxxxxx ...") and CR/LF seems to be ignored)

(2) Allow html messages -  `bootstrap` does this via a `boolean` `html` flag - although the bootstrap documentation also says 

> "Use text if you're worried about XSS attacks."

but I don't really know the risks and this feature is not so important.

(3) I've found that I need to display inline the tooltip as follows in every case because otherwise it displays as a block and the tooltip shows in the middle of the block 

```html
<div class="py-5">
    <label>Label : </label>
    <Tooltip Text="This is a tooltip">
        <label>Wrapped Item</label>
    </Tooltip>
</div>
```
Before 

![image](https://user-images.githubusercontent.com/26474006/65298199-c8ae0000-db94-11e9-9f66-65f3ddfc88a5.png)

After

```html
.b-tooltip {
    display: inline;
}
```

![image](https://user-images.githubusercontent.com/26474006/65298241-f5621780-db94-11e9-8058-83de3eb30733.png)


Regards

Brett

**Comment by stsrki** [comment]
Hi @brettwinters 

1. This should not be a problem
2. It would require a major rewrite of Tooltip so I would skip this feature for now.
3. This is possible when Blazorise components are used inside of `<Tooltip>`. But when there are native tags like `<label>` I cannot do much.

What I can do is to add `IsInline` attribute to `<Tooltip>` so that it can be controller manually if needed

**Comment by stsrki** [comment]
Most of the things is fixed with #376

**Comment by WillianGruber** [comment]
New release worked perfectly for tooltips, thank you @stsrki

**Comment by StephaneJourdois** [comment]
hi @stsrki, hi all

this tooltip issue is back with new release :)

-> Tooltip display an empty tooltip when Text is "" (or null).

Thanks for your work.

S.
